name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Install dependencies (adjust this as per your project)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (optional step to validate code)
    - name: Run tests
      run: |
        PYTHONPATH=. pytest

    # Step 5: Build your project (create a .zip artifact)
    - name: Build project
      run: |
        zip -r project-artifact.zip .

    # Step 6: Ensure the artifact has correct permissions
    - name: Set permissions on artifact
      run: |
        chmod 644 project-artifact.zip

    # Step 7: Upload build artifact to S3 using the correct syntax
    - name: Upload artifact to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        entryPoint: "aws s3 cp ./project-artifact.zip s3://your-project-build-artifacts/builds/project-artifact-${{ github.sha }}.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Step 1: Checkout code (same as above)
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Deploy to EC2 (using SSH)
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # SSH into the EC2 instance and deploy the project
          cd /path/to/your/app
          aws s3 cp s3://your-project-build-artifacts/builds/project-artifact-${{ github.sha }}.zip /tmp/project-artifact.zip
          unzip /tmp/project-artifact.zip -d /path/to/your/app
          # Add other deployment steps (restart services, etc.)
          sudo systemctl restart your-app-service
